apiVersion: v1
kind: Secret
metadata:
  namespace: hackapp
  labels: 
    team: dev-ops
    app: gitlab
  name: gitlab-secret
data:
  # To regenerate the secret use ``echo -n <content> | base64``

  # "password" is set as password
  root.password: cGFzc3dvcmQ=

  # "5J9_7cGphVXN9qm84rJ8" is set as initial token
  runners.token: NUo5XzdjR3BoVlhOOXFtODRySjg=
