apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner
  labels: 
    team: dev-ops
    app: gitlab-runner
  namespace: hackapp
spec:
  replicas: 1
  selector:
    matchLabels:
      team: dev-ops
      app: gitlab-runner
  template:
    metadata:
      labels: 
        team: dev-ops
        app: gitlab-runner
    spec:
      containers:
      - image: hackapp/gitlab-runner:v9.4.1
        imagePullPolicy: IfNotPresent
        name: gitlab-runner
        env:
        - name: REGISTRATION_TOKEN
          # Using gitlab secrets to get the initial token
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: runners.token
        envFrom:
        - configMapRef:
            name: gitlab-runner-config
        volumeMounts:
        - name: kubernetes-secret-volume
          readOnly: true
          mountPath: /etc/ssl/kubernetes/
      volumes:
      - name: kubernetes-secret-volume
        secret:
          secretName: kubernetes-certificates
    
      # Ensure that gitlab (CI_SERVER_URL) is reachable before starting the base pod
      initContainers:
      - name: init-myservice
        image: busybox:1.27.1
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE
          valueFrom:
            configMapKeyRef:
              name: gitlab-runner-config
              key: CI_SERVER_URL
        - name: TIMEOUT_S
          value: '120'
        command: ['/bin/sh', '-c', 'timeout -t ${TIMEOUT_S} sh -c "until wget -O - ${SERVICE} &> /dev/null; do echo Waiting for ${SERVICE}; sleep 1; done"']
