apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels: 
    team: dev-ops
    app: gitlab
  namespace: hackapp
spec:
  replicas: 1
  selector:
    matchLabels:
      team: dev-ops
      app: gitlab
  template:
    metadata:
      labels: 
        team: dev-ops
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:9.4.1-ce.0
        imagePullPolicy: IfNotPresent
        name: gitlab
        env:
        - name: GITLAB_ROOT_PASSWORD
          value: password
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GITLAB_OMNIBUS_CONFIG
          value: external_url 'http://$(POD_NAME).$(POD_NAMESPACE).svc.cluster.local'
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 22
          protocol: TCP
      terminationGracePeriodSeconds: 30
