apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner
  labels: 
    team: dev-ops
    app: gitlab-runner
  namespace: hackapp
spec:
  replicas: 1
  selector:
    matchLabels:
      team: dev-ops
      app: gitlab-runner
  template:
    metadata:
      labels: 
        team: dev-ops
        app: gitlab-runner
    spec:
      containers:
      - image: hackapp/gitlab-runner:v9.4.1
        imagePullPolicy: IfNotPresent
        name: gitlab-runner
        command: [
          "/usr/bin/dumb-init", "/custom-entrypoint",
        ]
        volumeMounts:
        - name: kubernetes-secret-volume
          mountPath: /etc/ssl/kubernetes/
        envFrom:
        - configMapRef:
            name: gitlab-runner-config
      volumes:
      - name: kubernetes-secret-volume
        secret:
          secretName: kubernetes-certificates
