apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: hackapp
data:

  GITLAB_ROOT_PASSWORD: password

  # Runner registration token (this will be used to auto register runners)
  GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: 5J9_7cGphVXN9qm84rJ8

  GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.hackapp.svc.cluster.local'"
