apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  labels: 
    team: dev-ops
    app: gitlab
  namespace: hackapp
data:
  CI_SERVER_URL: http://gitlab.hackapp.svc.cluster.local
  RUNNER_TAG_LIST: docker, deploy, test

  RUNNER_REQUEST_CONCURRENCY: '4'
  REGISTER_NON_INTERACTIVE: 'true'
  REGISTER_LOCKED: 'false'
  REGISTER_RUN_UNTAGGED: 'true'

  RUNNER_EXECUTOR: kubernetes
  KUBERNETES_HOST: kubernetes.default.svc.cluster.local
  KUBERNETES_CERT_FILE: /etc/ssl/kubernetes/apiserver.crt
  KUBERNETES_KEY_FILE: /etc/ssl/kubernetes/apiserver.key
  KUBERNETES_CA_FILE: /etc/ssl/kubernetes/ca.crt
  KUBERNETES_NAMESPACE: hackapp-ci
  KUBERNETES_PRIVILEGED: 'true' # NOTE: this could have negative impact on security!
