apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: hackapp
data:
  registration.token: 5J9_7cGphVXN9qm84rJ8  # Token retrieved by <gitlab>/admin/runners

  ci.server.url: http://gitlab.hackapp.svc.cluster.local
  runner.tag.list: deploy, test

  runner.request.concurrency: '4'
  register.non.interactive: 'true'
  register.locked: 'false'
  register.run.untagged: 'true'

  runner.executor: kubernetes
  kubernetes.host: kubernetes.default.svc.cluster.local
  kubernetes.cert.file: /etc/ssl/kubernetes/apiserver.crt
  kubernetes.key.file: /etc/ssl/kubernetes/apiserver.key
  kubernetes.ca.file: /etc/ssl/kubernetes/ca.crt
  kubernetes.namespace: hackapp-ci
  kubernetes.privileged: 'true' # NOTE: this could have negative impact on security!
