apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  labels: 
    team: dev-ops
    app: gitlab
  namespace: hackapp
data:
  GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.hackapp.svc.cluster.local'"
