apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels: 
    team: dev-ops
    app: gitlab
  namespace: hackapp
spec:
  selector:
    team: dev-ops 
    app: gitlab
  ports:
  - port: 80
    name: http
    protocol: TCP
    nodePort: 32000
  - port: 443
    name: https
    protocol: TCP
    nodePort: 32001
  - port: 22
    name: ssh
    protocol: TCP
    nodePort: 32002
  type: NodePort

status:
  loadBalancer: {}
