apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels: 
    app: hello-world
  namespace: hackapp
spec:
  selector: 
    app: hello-world
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31309
  type: NodePort

status:
  loadBalancer: {}
